import type { ProductTextureAsset } from '../domain/types';

const POLYHAVEN = {
  pine: {
    texture: 'https://dl.polyhaven.org/file/ph-assets/Textures/jpg/1k/wood_table/wood_table_diff_1k.jpg',
    source: 'https://polyhaven.com/a/wood_table',
  },
  coatedPine: {
    texture: 'https://dl.polyhaven.org/file/ph-assets/Textures/jpg/1k/coated_pine/coated_pine_diff_1k.jpg',
    source: 'https://polyhaven.com/a/coated_pine',
  },
  redBrown: {
    texture: 'https://dl.polyhaven.org/file/ph-assets/Textures/jpg/1k/wood_table_001/wood_table_001_diff_1k.jpg',
    source: 'https://polyhaven.com/a/wood_table_001',
  },
  lightGrain: {
    texture: 'https://dl.polyhaven.org/file/ph-assets/Textures/jpg/1k/okoume_veneer/okoume_veneer_diff_1k.jpg',
    source: 'https://polyhaven.com/a/okoume_veneer',
  },
  fineGrain: {
    texture: 'https://dl.polyhaven.org/file/ph-assets/Textures/jpg/1k/oak_veneer_01/oak_veneer_01_diff_1k.jpg',
    source: 'https://polyhaven.com/a/oak_veneer_01',
  },
} as const;

export const productTextures: ProductTextureAsset[] = [
  {
    id: 'tex-pin-nord-vert-lisse-close',
    boardIds: ['IDEA-TERR-G027'],
    label: 'Pin du Nord Classe 4 vert — rendu proche',
    materialFamily: 'wood',
    finishType: 'smooth',
    tone: 'vert autoclave',
    status: 'close',
    previewImageUrl: POLYHAVEN.pine.texture,
    textureImageUrl: POLYHAVEN.pine.texture,
    sourceLabel: 'Poly Haven — Wood Table (CC0)',
    sourceUrl: POLYHAVEN.pine.source,
    sourceLicense: 'CC0',
    referenceSourceUrl: 'https://www.idea-bois.com/art-lame-de-terrasse-en-pin-du-nord-lisse-long-3-00-m-27x145-mm-classe-4-2490.htm',
    textureScaleMmX: 1200,
    textureScaleMmY: 180,
    repeatMode: 'repeat',
    tintColor: '#6e7d59',
    tintOpacity: 0.36,
    notes: 'Texture proche : base pin CC0 recalibrée vers la teinte autoclave verte. Ne représente pas une photo exacte du produit IDEA Bois.',
  },
  {
    id: 'tex-pin-nord-vert-strie-close',
    boardIds: ['IDEA-TERR-G028'],
    label: 'Pin du Nord strié Classe 4 vert — rendu proche',
    materialFamily: 'wood',
    finishType: 'grooved',
    tone: 'vert autoclave',
    status: 'close',
    previewImageUrl: POLYHAVEN.coatedPine.texture,
    textureImageUrl: POLYHAVEN.coatedPine.texture,
    sourceLabel: 'Poly Haven — Coated Pine (CC0)',
    sourceUrl: POLYHAVEN.coatedPine.source,
    sourceLicense: 'CC0',
    referenceSourceUrl: 'https://www.idea-bois.com/art-terrasse-en-pin-du-nord-stri-3-00m-145x27-mm-3215.htm',
    textureScaleMmX: 1650,
    textureScaleMmY: 145,
    repeatMode: 'repeat',
    tintColor: '#7c8362',
    tintOpacity: 0.30,
    grooveCount: 26,
    notes: 'B1 : base pin noueuse CC0, teinte autoclave vert/olive et profil visuel à deux bandes de stries fortes.',
  },
  {
    id: 'tex-pin-nord-marron-lisse-close',
    boardIds: ['IDEA-TERR-G029','IDEA-TERR-G031'],
    label: 'Pin du Nord Classe 4 marron — rendu proche',
    materialFamily: 'wood',
    finishType: 'smooth',
    tone: 'marron',
    status: 'close',
    previewImageUrl: POLYHAVEN.pine.texture,
    textureImageUrl: POLYHAVEN.pine.texture,
    sourceLabel: 'Poly Haven — Wood Table (CC0)',
    sourceUrl: POLYHAVEN.pine.source,
    sourceLicense: 'CC0',
    referenceSourceUrl: 'https://www.idea-bois.com/art-lame-pin-du-nord-lisse-marron-l-3-00-m-145x27mm-traitement-classe-4-2172.htm',
    textureScaleMmX: 1200,
    textureScaleMmY: 180,
    repeatMode: 'repeat',
    tintColor: '#865c43',
    tintOpacity: 0.35,
    notes: 'Texture proche : base pin CC0 recalibrée vers le traitement marron.',
  },
  {
    id: 'tex-pin-nord-marron-strie-close',
    boardIds: ['IDEA-TERR-G030'],
    label: 'Pin du Nord strié Classe 4 marron — rendu proche',
    materialFamily: 'wood',
    finishType: 'grooved',
    tone: 'marron',
    status: 'close',
    previewImageUrl: POLYHAVEN.coatedPine.texture,
    textureImageUrl: POLYHAVEN.coatedPine.texture,
    sourceLabel: 'Poly Haven — Coated Pine (CC0)',
    sourceUrl: POLYHAVEN.coatedPine.source,
    sourceLicense: 'CC0',
    referenceSourceUrl: 'https://www.idea-bois.com/art-lame-de-terrasse-en-pin-du-nord-strie-classe-4-marron-l-3-00-m-145x27-mm.htm',
    textureScaleMmX: 1650,
    textureScaleMmY: 145,
    repeatMode: 'repeat',
    tintColor: '#8a5b3f',
    tintOpacity: 0.33,
    grooveCount: 26,
    notes: 'B1 : base pin noueuse CC0, teinte autoclave marron et profil visuel à deux bandes de stries fortes.',
  },
  {
    id: 'tex-cumaru-close',
    boardIds: ['IDEA-TERR-G003','IDEA-TERR-G004','IDEA-TERR-G005'],
    label: 'Cumaru — rendu proche',
    materialFamily: 'wood',
    finishType: 'smooth',
    tone: 'brun doré à brun rougeâtre',
    status: 'close',
    previewImageUrl: POLYHAVEN.redBrown.texture,
    textureImageUrl: POLYHAVEN.redBrown.texture,
    sourceLabel: 'Poly Haven — Wood Table 001 (CC0)',
    sourceUrl: POLYHAVEN.redBrown.source,
    sourceLicense: 'CC0',
    referenceSourceUrl: 'https://lightbeans.com/en/texture/platinum-woods/cumaru-decking-square-edge',
    textureScaleMmX: 1100,
    textureScaleMmY: 170,
    repeatMode: 'repeat',
    tintColor: '#7d4934',
    tintOpacity: 0.22,
    notes: 'Texture proche. La référence de comparaison est un matériau de terrasse Cumaru, pas la lame IDEA Bois exacte.',
  },
  {
    id: 'tex-garapa-close',
    boardIds: ['IDEA-TERR-G006','IDEA-TERR-G007','IDEA-TERR-G008','IDEA-TERR-G009'],
    label: 'Garapa — rendu proche',
    materialFamily: 'wood',
    finishType: 'smooth',
    tone: 'jaune doré / miel',
    status: 'close',
    previewImageUrl: POLYHAVEN.lightGrain.texture,
    textureImageUrl: POLYHAVEN.lightGrain.texture,
    sourceLabel: 'Poly Haven — Okoume Veneer (CC0)',
    sourceUrl: POLYHAVEN.lightGrain.source,
    sourceLicense: 'CC0',
    referenceSourceUrl: 'https://lightbeans.com/en/texture/platinum-woods/garapa-decking-square-edge',
    textureScaleMmX: 1100,
    textureScaleMmY: 170,
    repeatMode: 'repeat',
    tintColor: '#c39a52',
    tintOpacity: 0.28,
    notes: 'Texture proche calibrée vers le ton Garapa. Le matériau de référence Lightbeans confirme une texture de terrasse Garapa.',
  },
  {
    id: 'tex-ipe-close',
    boardIds: ['IDEA-TERR-G010','IDEA-TERR-G011'],
    label: 'Ipé — rendu proche',
    materialFamily: 'wood',
    finishType: 'smooth',
    tone: 'brun profond',
    status: 'close',
    previewImageUrl: POLYHAVEN.redBrown.texture,
    textureImageUrl: POLYHAVEN.redBrown.texture,
    sourceLabel: 'Poly Haven — Wood Table 001 (CC0)',
    sourceUrl: POLYHAVEN.redBrown.source,
    sourceLicense: 'CC0',
    referenceSourceUrl: 'https://lightbeans.com/en/texture/platinum-woods/ipe-decking-grooved-on-two-sides',
    textureScaleMmX: 1150,
    textureScaleMmY: 165,
    repeatMode: 'repeat',
    tintColor: '#543b30',
    tintOpacity: 0.35,
    notes: 'Texture proche : teinte sombre calibrée à partir d’une base CC0. La texture de référence Ipe est issue d’une bibliothèque de matériaux de terrasse.',
  },
  {
    id: 'tex-padouk-close',
    boardIds: ['IDEA-TERR-G014','IDEA-TERR-G015','IDEA-TERR-G016'],
    label: 'Padouk — rendu proche',
    materialFamily: 'wood',
    finishType: 'smooth',
    tone: 'rouge-orangé',
    status: 'close',
    previewImageUrl: POLYHAVEN.redBrown.texture,
    textureImageUrl: POLYHAVEN.redBrown.texture,
    sourceLabel: 'Poly Haven — Wood Table 001 (CC0)',
    sourceUrl: POLYHAVEN.redBrown.source,
    sourceLicense: 'CC0',
    referenceSourceUrl: 'https://www.arroway-textures.ch/products/wood-069v2/',
    textureScaleMmX: 1000,
    textureScaleMmY: 150,
    repeatMode: 'repeat',
    tintColor: '#a9422f',
    tintOpacity: 0.34,
    notes: 'Texture proche : Padouk identifiable par sa dominante rouge-orangé ; la texture exacte de la lame IDEA Bois n’est pas revendiquée.',
  },
  {
    id: 'tex-silvadec-gris-close',
    boardIds: ['IDEA-TERR-G037'],
    label: 'SILVADEC Atmosphère Gris Ushuaia — rendu proche',
    materialFamily: 'composite',
    finishType: 'brushed',
    tone: 'gris',
    status: 'close',
    previewImageUrl: POLYHAVEN.fineGrain.texture,
    textureImageUrl: POLYHAVEN.fineGrain.texture,
    sourceLabel: 'Poly Haven — Oak Veneer 01 (CC0), utilisé uniquement comme base de relief visuel',
    sourceUrl: POLYHAVEN.fineGrain.source,
    sourceLicense: 'CC0',
    referenceSourceUrl: 'https://www.idea-bois.com/art-lame-composite-atmosph-re-bross-e-23x138x4000-mm-gris-ushuaia-silvadec-1845.htm',
    textureScaleMmX: 900,
    textureScaleMmY: 160,
    repeatMode: 'repeat',
    tintColor: '#6f7477',
    tintOpacity: 0.68,
    notes: 'Texture proche, volontairement non qualifiée d’exacte. La teinte et la finition correspondent à la variante Gris Ushuaia.',
  },
  {
    id: 'tex-silvadec-ipe-close',
    boardIds: ['IDEA-TERR-G038'],
    label: 'SILVADEC Atmosphère Nuances Ipé — rendu proche',
    materialFamily: 'composite',
    finishType: 'structured',
    tone: 'brun ipé',
    status: 'close',
    previewImageUrl: POLYHAVEN.fineGrain.texture,
    textureImageUrl: POLYHAVEN.fineGrain.texture,
    sourceLabel: 'Poly Haven — Oak Veneer 01 (CC0), utilisé uniquement comme base de relief visuel',
    sourceUrl: POLYHAVEN.fineGrain.source,
    sourceLicense: 'CC0',
    referenceSourceUrl: 'https://www.idea-bois.com/art-lame-composite-atmosph-re-nuances-ip-23x138x4000-mm-silvadec-3416.htm',
    textureScaleMmX: 900,
    textureScaleMmY: 160,
    repeatMode: 'repeat',
    tintColor: '#73523f',
    tintOpacity: 0.52,
    notes: 'Texture proche, pas une texture fabricant SILVADEC exacte.',
  },
];

export const neutralTexture: ProductTextureAsset = {
  id: 'texture-neutral',
  boardIds: [],
  label: 'Texture à compléter',
  materialFamily: 'other',
  finishType: 'other',
  tone: 'neutre',
  status: 'neutral',
  sourceLabel: 'Aucune texture validée',
  textureScaleMmX: 1000,
  textureScaleMmY: 160,
  repeatMode: 'repeat',
  notes: 'Aucune approximation visuelle n’est présentée comme produit réel.',
};
